{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ include "kas.name" . }}
type: Opaque
data:
  # Token
  agent.token: {{ .Values.secret.agent.token | b64enc | quote }}
    
  # Websocket
  websocket.url: {{ .Values.secret.websocket.url | b64enc | quote }}
  
{{- end }}